extends:
  - airbnb-base
  - "plugin:flowtype/recommended"
plugins: [flowtype]
rules:
  indent: [error, 4, { MemberExpression: 0 }]
  function-paren-newline: 0
  no-underscore-dangle: 0
  class-methods-use-this: 0
  guard-for-in: 0
  no-restricted-syntax: 0
  comma-dangle: 0
  no-undef: 0
  no-unused-expressions: 0
  dot-location: [error, object]
  max-len: [error, 120]
